document.addEventListener('DOMContentLoaded', () => {
  const svgInput = document.getElementById('svgInput');
  const svgOutput = document.getElementById('svgOutput');
  const fileInput = document.getElementById('fileInput');
  const dropZone = document.getElementById('dropZone');
  const btnOptimize = document.getElementById('btnOptimize');
  const btnPreset = document.getElementById('btnPreset');
  const btnCopy = document.getElementById('btnCopy');
  const btnDownload = document.getElementById('btnDownload');
  const svgPreview = document.getElementById('svgPreview');

  const origSizeEl = document.getElementById('origSize');
  const optSizeEl = document.getElementById('optSize');
  const sizeSavingsEl = document.getElementById('sizeSavings');

  // Options
  const optComments = document.getElementById('optComments');
  const optMetadata = document.getElementById('optMetadata');
  const optEmptyGroups = document.getElementById('optEmptyGroups');
  const optWhitespace = document.getElementById('optWhitespace');
  const optPrecision = document.getElementById('optPrecision');
  const decimalDigits = document.getElementById('decimalDigits');
  const scaleFactor = document.getElementById('scaleFactor');

  const SAMPLE_SVG = `<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 200 200" width="200" height="200">
  <!-- Generated by Illustrator CS6 (SVG Export Plugin) -->
  <metadata id="inkscape-metadata-001">
    <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
      <work rdf:about="" />
    </rdf:RDF>
  </metadata>
  <g id="Layer_1">
    <g id="Empty_Group_Container"></g>
    <!-- Background Circle -->
    <circle cx="100.0000" cy="100.0000" r="85.4521" fill="#ec4899" stroke="#8b5cf6" stroke-width="4.12345" />
    <!-- Star Path -->
    <path d="M 100.1234 35.8765 L 118.4321 72.1987 L 158.9876 78.1122 L 129.6543 106.7890 L 136.5432 147.2345 L 100.0000 128.0000 L 63.4567 147.2345 L 70.3456 106.7890 L 41.0123 78.1122 L 81.5678 72.1987 Z" fill="#ffffff" />
  </g>
</svg>`;

  function optimizeSVG() {
    let raw = svgInput.value.trim();
    if (!raw) {
      svgOutput.value = '';
      svgPreview.innerHTML = '<span class="placeholder-text">Rendered vector preview will appear here</span>';
      updateStats(0, 0);
      return;
    }

    const origBytes = new Blob([raw]).size;

    // 1. Remove Comments & DocType
    if (optComments.checked) {
      raw = raw.replace(/<!--[\s\S]*?-->/g, '');
      raw = raw.replace(/<\?xml[\s\S]*?\?>/g, '');
      raw = raw.replace(/<!DOCTYPE[\s\S]*?>/gi, '');
    }

    // 2. Remove Editor Metadata
    if (optMetadata.checked) {
      raw = raw.replace(/<metadata[\s\S]*?<\/metadata>/gi, '');
      raw = raw.replace(/xmlns:dc="[^"]*"/gi, '');
      raw = raw.replace(/xmlns:cc="[^"]*"/gi, '');
      raw = raw.replace(/xmlns:rdf="[^"]*"/gi, '');
      raw = raw.replace(/xmlns:svg="[^"]*"/gi, '');
      raw = raw.replace(/xmlns:sodipodi="[^"]*"/gi, '');
      raw = raw.replace(/xmlns:inkscape="[^"]*"/gi, '');
      raw = raw.replace(/inkscape:[a-z-]+="[^"]*"/gi, '');
      raw = raw.replace(/sodipodi:[a-z-]+="[^"]*"/gi, '');
    }

    // 3. Remove Empty Groups
    if (optEmptyGroups.checked) {
      raw = raw.replace(/<g[^>]*>\s*<\/g>/gi, '');
    }

    // 4. Decimal Precision Reduction
    if (optPrecision.checked) {
      const precision = parseInt(decimalDigits.value, 10);
      raw = raw.replace(/(-?\d+\.\d+)/g, (match) => {
        const num = parseFloat(match);
        return isNaN(num) ? match : Number(num.toFixed(precision)).toString();
      });
    }

    // 5. Scaling Vector Factor
    const scale = parseFloat(scaleFactor.value);
    if (scale !== 1.0) {
      // Modify viewBox width/height
      raw = raw.replace(/viewBox=["']([0-9.\s]+)["']/i, (match, p1) => {
        const parts = p1.trim().split(/\s+/).map(Number);
        if (parts.length === 4) {
          parts[2] = Number((parts[2] * scale).toFixed(2));
          parts[3] = Number((parts[3] * scale).toFixed(2));
          return `viewBox="${parts.join(' ')}"`;
        }
        return match;
      });
    }

    // 6. Minify Whitespace
    if (optWhitespace.checked) {
      raw = raw.replace(/>\s+</g, '><');
      raw = raw.replace(/\s+/g, ' ');
      raw = raw.trim();
    }

    const optBytes = new Blob([raw]).size;

    svgOutput.value = raw;
    svgPreview.innerHTML = raw;

    updateStats(origBytes, optBytes);
  }

  function updateStats(orig, opt) {
    origSizeEl.textContent = formatBytes(orig);
    optSizeEl.textContent = formatBytes(opt);

    if (orig > 0 && opt >= 0) {
      const saved = ((orig - opt) / orig) * 100;
      sizeSavingsEl.textContent = `${Math.max(0, Math.round(saved))}% Saved`;
    } else {
      sizeSavingsEl.textContent = '0%';
    }
  }

  function formatBytes(bytes) {
    if (bytes === 0) return '0 B';
    const k = 1024;
    const sizes = ['B', 'KB', 'MB'];
    const i = Math.floor(Math.log(bytes) / Math.log(k));
    return parseFloat((bytes / Math.pow(k, i)).toFixed(1)) + ' ' + sizes[i];
  }

  // File Drag & Drop
  dropZone.addEventListener('dragover', (e) => {
    e.preventDefault();
    dropZone.classList.add('dragover');
  });

  dropZone.addEventListener('dragleave', () => {
    dropZone.classList.remove('dragover');
  });

  dropZone.addEventListener('drop', (e) => {
    e.preventDefault();
    dropZone.classList.remove('dragover');
    if (e.dataTransfer.files.length > 0) {
      readFile(e.dataTransfer.files[0]);
    }
  });

  fileInput.addEventListener('change', (e) => {
    if (e.target.files.length > 0) {
      readFile(e.target.files[0]);
    }
  });

  function readFile(file) {
    if (!file.name.endsWith('.svg') && file.type !== 'image/svg+xml') {
      alert('Please upload a valid .svg file');
      return;
    }
    const reader = new FileReader();
    reader.onload = (evt) => {
      svgInput.value = evt.target.result;
      optimizeSVG();
    };
    reader.readAsText(file);
  }

  btnPreset.addEventListener('click', () => {
    svgInput.value = SAMPLE_SVG;
    optimizeSVG();
  });

  btnOptimize.addEventListener('click', optimizeSVG);

  btnCopy.addEventListener('click', () => {
    if (!svgOutput.value) return;
    navigator.clipboard.writeText(svgOutput.value).then(() => {
      btnCopy.textContent = '✓ Copied!';
      setTimeout(() => btnCopy.textContent = '📋 Copy SVG', 2000);
    });
  });

  btnDownload.addEventListener('click', () => {
    if (!svgOutput.value) return;
    const blob = new Blob([svgOutput.value], { type: 'image/svg+xml' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'optimized-vector.svg';
    a.click();
    URL.revokeObjectURL(url);
  });

  // Attach live options change
  [optComments, optMetadata, optEmptyGroups, optWhitespace, optPrecision, decimalDigits, scaleFactor, svgInput].forEach(el => {
    el.addEventListener('input', optimizeSVG);
    el.addEventListener('change', optimizeSVG);
  });

  // Load sample on start
  svgInput.value = SAMPLE_SVG;
  optimizeSVG();
});

// Global Toast Notification Helper
window.showToast = function(message) {
  let toast = document.getElementById('globalToast');
  if (!toast) {
    toast = document.createElement('div');
    toast.id = 'globalToast';
    toast.style.cssText = 'position:fixed;bottom:24px;right:24px;background:rgba(16,185,129,0.95);color:#000;padding:12px 20px;border-radius:10px;font-weight:700;box-shadow:0 10px 30px rgba(0,0,0,0.5);z-index:9999;transition:all 0.3s ease;transform:translateY(100px);opacity:0;backdrop-filter:blur(10px);';
    document.body.appendChild(toast);
  }
  toast.textContent = message;
  toast.style.transform = 'translateY(0)';
  toast.style.opacity = '1';
  setTimeout(() => {
    toast.style.transform = 'translateY(100px)';
    toast.style.opacity = '0';
  }, 3000);
};

  // DOM XSS Sanitizer for SVG Preview
  function sanitizeSVG(svgString) {
    return svgString
      .replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
      .replace(/on\w+="[^"]*"/gi, '')
      .replace(/on\w+='[^']*'/gi, '')
      .replace(/javascript:/gi, '');
  }
